
version: '3.3'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: mango-diary
    volumes:
      - .:/code
      - app_data:/data
    ports:
      - 3333:3333
    depends_on:
      - db
      
volumes:
  postgres_data:
  app_data: